### PR TITLE
[MFLOW STEPS] - Genlib step for Synopsys PT tool 

### PR DESCRIPTION
**Pull request by Gu3nol**
Extend the corners to best and worst case in the lib generation

The extra corners are defined in the designer interface which is
now sourced by the START script

By default, the corner " " corresponding to the default is analyzed
and the corresponding outputs produced and tested in the configure.yml

TODO: Since the outputs of the step depends on the corners used,
a parameter should be added to the configure.yml to extend the
necessary inputs and tests the proper outputs.

### CODE REVIEW

**Comment by ctorng** [comment]
Hm, so the way you have it set up now looks like you want to use a single genlibdb node to do _all_ corners. I think you should instead just create three nodes if you have three corners. So pass the best case spef/lib/db into the best case genlibdb node. This makes the genlibdb node simpler while making the graph construction marginally more complex. Can we do that instead?

**Comment by Gu3nol** [comment]
OK. I will keep my custom step then. :)

Yet, I honestly don't understand why you want to multiply the number of
step.

In a "non-academic" SoC validation, the number of corners can be
significant depending on all the operating conditions, aging, etc....
Consequently, the number of genlibdb could be quite huge. In order to scale
mflowgen, I still believe in should be done in one step.

Guénolé.


--

Guénolé LALLEMENT
guenole.lallement@gmail.com

**Comment by ctorng** [comment]
I am not sure which way is more natural. It is a loop either way...

1. The loop is built into the step like in this pull request
2. The loop is in the graph (instantiates the same step multiple times)

You either make the node more complex by putting the loop inside it, or you make it simpler but put the loop outside of it. They both address the issue but in slightly different ways. I think the simple node is a bit more mflowgen-ic.

**Comment by ctorng** [comment]
Okay, the decision for now is to leave this unmerged, and we see how it works for your project first.

The other thing we discussed on the call that is not mentioned here is that if we make the loop part of the graph, then you can parallelize jobs with "make -j".

Let's wait to see how things go.

**Pull request closed without merging**
