### PR TITLE
Easysteps

### PR DESCRIPTION
**Pull request by steveri**
This pull has been abandoned in favor of the similar garnet-repo pull https://github.com/StanfordAHA/garnet/pull/757 . The new plan is for all this functionality to reside as part of a specific project (in this case, `garnet`). I will be deleting this pull once the changeover is complete/stable.

<s>
So...for some time now I have thought it would be useful to simplify the way we build `construct.py` scripts for new flows...it seemed to me that there was a lot of duplicated/unnecessary extra effort involved for various simple tasks. 

Currently, adding a node/step involves modifying your `construct.py` script in three separate places: once to define the node, once to add the node to the graph, and once to connect it to the other nodes in the graph. For example, adding a couple of default nodes `iflow` and `init` currently looks like the code below (all "before" examples are taken from the `construct.py` in our Tile_PE flow).
```
    # Adding default nodes BEFORE:

    iflow  = Step( 'cadence-innovus-flowsetup', default=True )
    init   = Step( 'cadence-innovus-init',      default=True )
    power  = Step( 'cadence-innovus-power',     default=True )

    ...
    g.add_step( iflow )
    g.add_step( init  )
    g.add_step( power )
    ...
    g.connect_by_name( iflow,    init         )
    g.connect_by_name( iflow,    power        )
    g.connect_by_name( iflow,    place        )
    g.connect_by_name( iflow,    cts          )
    g.connect_by_name( iflow,    postcts_hold )
    g.connect_by_name( iflow,    route        )
    g.connect_by_name( iflow,    postroute    )
    g.connect_by_name( iflow,    signoff      )
    g.connect_by_name( init,     power        )
    ...
    g.connect_by_name( power,        place        )
```

I propose combining all these steps in a single place in the script, e.g. something like
```
    # Adding default nodes AFTER:
  
    g.add_default_steps('''
      init  - cadence-innovus-init      -> power
      power - cadence-innovus-power     -> place
      iflow - cadence-innovus-flowsetup
              -> init power place cts postcts_hold
              -> route postroute signoff debugcalibre
      ''')
```
The string passed to this new function `add_default_steps()`, yaml-like in simplicity, would be parsed and expanded, invisibly to the user, into the full `Step()/add_step()/connect_by_name()` sequence.

Similarly, code for custom nodes might change as follows
```
    # Custom nodes BEFORE

    rtl          = Step( this_dir + '/../common/rtl' )
    constraints  = Step( this_dir + '/constraints'   )
    ...
    g.add_step( rtl         )
    g.add_step( constraints )
    ...
    g.connect_by_name( rtl,         synth )
    g.connect_by_name( constraints, synth )
    g.connect_by_name( constraints, iflow )
    ...

---
    # Custom nodes AFTER

    g.add_custom_steps('''
      rtl         - ../common/rtl -> synth
      constraints - constraints   -> synth iflow
      ''')
```
...and then this, for something I call "custom extend-only nodes," where a custom extend-only step is a new node whose only purpose is to supply extra custom inputs to an existing node.
```
    # Custom extend-only nodes BEFORE

    custom_init  = Step( this_dir + '/custom-init'                           )
    custom_power = Step( this_dir + '/../common/custom-power-leaf'           )
    ...
    init.extend_inputs( custom_init.all_outputs() )
    power.extend_inputs( custom_power.all_outputs() )
    ...
    g.add_step( custom_init  )
    g.add_step( custom_power )
    ...
    g.connect_by_name( custom_init,  init  )
    g.connect_by_name( custom_power, power )

---
    # Custom extend-only steps AFTER

    g.extend_steps('''
       custom_init    custom-init                 -> init
       custom_power - ../common/custom-power-leaf -> power
       ''')
---
    # Or, could be done as two separate calls
  
    g.extend_steps('custom-init                 custom_init  -> init')
    g.extend_steps('../common/custom-power-leaf custom_power -> power')
```

See your email and/or kiwi:~steveri/0notes/vto/simplify/demo/{before,after}/construct.py for "before" and "after" examples of a Tile_PE/construct.py script using easysteps. The "before" file has 300 lines of code and the "after" has 200. For a more detailed/exact comparison, see the garnet easysteps-> master pull https://github.com/StanfordAHA/garnet/pull/757

Also in this pull: Updates to several output functions for better repeatability. In many places, mflowgen will print unordered lists such that two successive runs can produce very different output files, even if the changes between runs were minimal or even nil. I added some minimal sorting here and there to try and reduce the unnecessary randomness. This proved invaluable in completing and verifying the functional changes for easysteps.

</s>

### CODE REVIEW

**Comment by ctorng** [comment]
My initial thought on this is that it may overlap with some changes I am planning to make submodular nodes less clunky. At least for that reason, I am not sure I want this pull request to go in in the short term. Part of this pull request is actually about that clunkiness (e.g., connecting a new custom node into a graph).

I like the idea of enabling shorthand for basic graph building.

Note that almost all of our graphs are MORE explicit by our choice (?) and often do not use shortcuts even when available. For example, this code:

```
    g.connect_by_name( iflow,    init         )
    g.connect_by_name( iflow,    power        )
    g.connect_by_name( iflow,    place        )
    g.connect_by_name( iflow,    cts          )
    g.connect_by_name( iflow,    postcts_hold )
    g.connect_by_name( iflow,    route        )
    g.connect_by_name( iflow,    postroute    )
    g.connect_by_name( iflow,    signoff      )
```

Should really just loop in two lines:

```
    for _ in [ init, power, place, cts, postcts_hold, route, postroute, signoff ]:
      g.connect_by_name( iflow,    _ )
```

And there is a lot of "unrolled" code like this in our graphs...

Maybe people just prefer being explicit in our current graphs? My guess is that people building graphs right now just like to see a list of edges... Also many graphs are not that big, so the extra readability becomes more worthwhile and the verbosity doesn't detract.

**My final opinion is:**

- I think this layer might be better as a project-specific layer above mflowgen
- I think it would be good to keep any sorting / determinacy changes you had to do to make it work

Thoughts?

**Comment by steveri** [comment]
@ctorng thanks very much for your feedback! I had meant to advertise this package yesterday with general email to group, but got waylaid by the last-minute realization that it wasn't passing the mflowgen travis tests. (That's working now, took me way longer than it should have.)

I'm glad you like the sorting changes for determinacy, I think I will wrap them as a separate pull.

I understand your desire to keep mflowgen clean and will start looking into how this could be a separate project-specific layer, as you call it. Now that it's working, pulling it out as a separate non-mflowgen-repo package shouldn't be too hard.

I'll send out mail in the next day or two summarizing my thoughts on the future of this project...

**Comment by steveri** [comment]
> Should really just loop in two lines:
> 
> ```
>     for _ in [ init, power, place, cts, postcts_hold, route, postroute, signoff ]:
>       g.connect_by_name( iflow,    _ )
> ```

@ctorng having the loop for `connect_by_name()` is a good alternative. However, for me the biggest advantage of something like "easysteps" is, when adding a new step/node, the ability to do all three required stages `Step()`, `add_step()`, and `connect_by_name()` together in one place, and with a single line of code...kind of moving it more towards a "single source of truth" within the script as opposed to being distributed around various parts of the script, even though they all belong together, if you know what I mean...
``` 
    g.add_default_steps("init - cadence-innovus-init  -> power")
    g.add_default_steps("power - cadence-innovus-power -> place" )
```

**Comment by steveri** [comment]
This pull has been abandoned in favor of the similar garnet-repo pull https://github.com/StanfordAHA/garnet/pull/757 . The new plan is for the `easysteps` functionality to reside as part of a specific project (in this case, `garnet`). I will be deleting this pull once the changeover is complete/stable.

**Pull request closed without merging**
